console.log('abe');
console.log('jaime');
console.log('Marcus');
console.log('Alexsa');
console.log('Felecia');
console.log('Galekwan Sango');
console.log("shanitrice");
console.log('Liubov');
console.log('eliza');
console.log('Amad');